SELECT d.SCORE as `SCORE`, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS d
JOIN HR_EMPLOYEES AS b ON d.EMP_NO = b.EMP_NO
WHERE d.SCORE = (
    SELECT MAX(SUM_SCORE)
    FROM (
        SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS t
)
