SELECT DATETIME "시간"
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1;

/** 너무 LIMIT으로만 문제를 푸는 거 같아서 Max를 사용해보기로 했다..

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
)
