SELECT e.QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT ID,
    CASE
        WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN "1Q"
        WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN "2Q"
        WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN "3Q"
        WHEN MONTH(DIFFERENTIATION_DATE) <= 12 THEN "4Q"
    END AS QUARTER
    FROM ECOLI_DATA
) AS e
GROUP BY 1
ORDER BY 1;
