#개발자의 id, 이메일, 이름, 성 조회하는 sql
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS as a
WHERE (SKILL_CODE & 1024 > 0) or (SKILL_CODE & 256) > 0
ORDER BY ID;

# 다른 문제 풀이
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) > 0
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID;
